edgee-cloud/edgee

src/entrypoint/web.rs

Redirect URI field in 3xx should be 'Location' as defined in https://datatracker.ietf.org/doc/html/rfc2616#section-14.30

web.rs: fix invalid location header

---

Cargo.lock
Cargo.toml
README.md
src/config.rs

Adds support for deserializing YAML config files via [serde_yml](https://crates.io/crates/serde_yml).
Now, users can choose to provide a `edgee.yaml` file instead of the `edgee.toml`.
None.

feat: support yaml config files

---

src/entrypoint.rs

The `Content-Length` header was not updated when returning the modified response, which lead to failed a "sanity check" in `hyper` when building in debug mode.
The fix is located on the `build_response` function by modifying the `http::HeaderMap` of the response parts (using `insert` which actually *replace* the name-value pair instead of appending it, as headers are multi-valued with some exceptions)

fix(entrypoint): Update Content-Length header to correct size

---

src/entrypoint.rs

Changed this from
https://github.com/edgee-cloud/edgee/blob/e3ccb3a1431087528e8cb5b17da5a610a62d5652/src/entrypoint.rs#L558
To
`parts.headers.insert("content-length", body.len().into());`
Expected HeaderValue, found usize https://github.com/edgee-cloud/edgee/issues/37

chore: changed uszie to HeaderValue

---

.github/workflows/publish.yml

Remove GitHub flake publishing action. It's not useful for now
No issue

chore: remove unused flake publishing

---

edgee.sample.toml
src/config/config.rs
src/proxy/compute/compute.rs

To maximize Edgee’s efficiency, it is best to ensure that computed content is not cacheable by browsers or shared caches.
However, upstream servers may add cache-control directives that are difficult to modify or remove.
In such cases, you can override the cache-control directive with a no-store policy to prevent content from being cached.
#74

feat: option to enforce no-store cache policy

---

src/config/config.rs

Running all the unit tests would fail occasionally (roughly 1 out of 10), either decrypt_failed_decryption or decrypt_valid_text would fail:
(Running on an M1 Macbook pro)
```
...
test tools::real_ip::tests::is_private_address_returns_false_for_public_ip ... ok
test tools::real_ip::tests::is_private_address_returns_true_for_private_ip ... ok
test tools::real_ip::tests::new_realip_initializes_with_private_cidrs ... ok
test tools::crypto::tests::decrypt_valid_text ... FAILED
failures:
---- tools::crypto::tests::decrypt_valid_text stdout ----
thread 'tools::crypto::tests::decrypt_valid_text' panicked at src/config/config.rs:253:28:
Should initialize config: InitializingError(StaticConfiguration { log: LogConfiguration { level: "info" }, http: Some(HttpConfiguration { address: …
```

Cargo test fails occasionally when running all tests

---

Cargo.lock
Cargo.toml
src/config/config.rs
src/main.rs

- Also add CLI options parsing base
- Add CLI options parsing
- Add `--config/-f` CLI flags for specifying a provided configuration file, preceding any default configuration path (`edgee.toml` and `edgee.yaml`)
- #36

feat: Allow Specifying a Config File Path on Execution

---

src/proxy/compute/compute.rs
src/proxy/controller/controller.rs
src/proxy/proxy.rs
src/tools/edgee_cookie.rs

Data collection components always received session_start instructions... There was an error redefining the user cookie at each request.
This pull request introduces several improvements and fixes to the `edgee_cookies.rs`, `compute.rs`, `controller.rs`, and `proxy.rs` files. The changes aim to enhance the handling of cookies, improve payload processing, and ensure better compliance with the application's requirements.
**Changes:**
1. **`edgee_cookies.rs`:**
- The methods of this script are now requiring a `response_parts` parameter instead of `response_headers`
2. **`compute.rs`:**
- edgee_cookie::get can now use the `response_parts` parameter instead of `response_headers`, and it fixes the bug we had on the session cookie set.
3. **`controller.rs`:**
- Improved the `edgee_client_event` …

fix: Cookie Handling and Payload Processing

---

src/proxy/compute/data_collection/components.rs
src/proxy/compute/data_collection/payload.rs

Interpretation of `destinations` node of the context payload for the data-collection wasm component
#93

feat: destinations node interpretation for wasm components

---

src/proxy/compute/data_collection/components.rs
src/proxy/compute/data_collection/components/context.rs
src/proxy/compute/data_collection/components/convert.rs
src/proxy/compute/data_collection/components/mod.rs
src/proxy/compute/data_collection/data_collection.rs

- Enable the `async` toggle in wasmtime component codegen for getting full async API
- Call data collection in a separate tokio task as to not blocking request handling
- Pre-instantiate data collection components at startup (make startup of `edgee` taking a bit longer as compromise)
- Cleanup components code
- Move payload processing into a dedicated module and make use of Rust `From` trait
- Move code out of `loop {}` to only compute once some values
- Remove some `.unwrap()` by re-using already computed values
- #92

perf(data_collection): Make Data-Collection Component Calls Asynchronous

---

Cargo.lock
Cargo.toml
src/config/config.rs
src/logger.rs
src/main.rs
src/proxy/compute/data_collection/components/mod.rs
src/proxy/compute/data_collection/data_collection.rs

Feature to debug a component easily
Developing a component is not easy, especially if we can't see anything. 
Now, we can launch edgee with a specific option `--debug-component=<component name>` and edgee will only print the content of the requests sent by the component, and the result of the analytics provider.
No issue

feat: component debug feature

---

src/proxy/controller.rs
src/tools/edgee_cookie.rs

Backend Set-Cookie were overriden when setting the edgee cookie, this fix append a new Set-Cookie header for the edgee cookie.
Tested against a Flask backend which sets a cookie on each request:
```
response.headers before: "set-cookie": "my_cookie=cookie_value; HttpOnly; Path=/"
response.headers after: "set-cookie": "my_cookie=cookie_value; HttpOnly; Path=/", "set-cookie": "edgee=f549f7f14c02725c9d7f6f0d520ae6dc79bed4beeedcde01b77ea43a5573788e97cd64ff976d930227469b7bf3f45afa9d7cfd1d1a4eafae08b92152c3d0dd16333779d8186d1a94e68fe9e1b34d34ce27a3c1f810e7eb404339a1d37996be483cb730b5f037cba1fdd5aec759a7416ed89bc5fba4232efcde7416f6b21d6c86bcc46a0eafb864ac900806c2ec6a29a23a5284c129d50c6de0235ef36768c4e0d9b8d2f17c67efbc066979b43c9eac9ad0c999fc83d9841af3c3cd9c374b434bba64a8468d1c99d5abdef093ddef2e13 …
```

fix: do not override backend set-cookie when setting edgee cookie

---

src/config.rs
src/tools/edgee_cookie.rs

When Edgee is installed in a complex network routing, it could listen to a specific host which is not the same than the one used by the client. 
In that case, edgee user must be able to specify a cookie_domain.

fix: add cookie_domain option

---

src/proxy/controller.rs
src/proxy/mod.rs

Returns 410 Gone for GET requests to data collection endpoints (`/_edgee/event`, `/_edgee/csevent`, and generated data collection paths) to prevent search engine indexing. Only POST requests with `application/json` content-type are valid for these endpoints.
- Updated condition checks in `handle_request` to return `empty_json_response` (410 Gone) for non-POST requests
- Maintains existing behavior for POST/OPTIONS requests
- Add "X-Robots-Tag: noindex, nofollow" header
#139

feat: Prevent search engine indexing of data collection endpoints

---

Cargo.lock
Cargo.toml

Now Edgee is ready to have a real CLI experience, I suggest creating the v0.6.0 to prepare for the next v1.0.0
I take this opportunity to bump the edgee-path version as well.
No issue

chore: bump edgee to version v0.6.0

---

crates/server/src/proxy/compute/data_collection/components/convert.rs
crates/server/wit/protocols.wit

For now, Edgee data collection components can only collect standard events (pageviews, identify, simple custom event). To be complete, a user has to be able to send e-commerce data to his analytics providers. 
Following the [GA4 e-commerce spec](https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?hl=en&client_type=gtag) and [Segment doc](https://segment.com/docs/connections/spec/ecommerce/v2/), I added the interpretation of a `products` array in the `data.properties` of a track event. 
No issue

feat: products properties

---

crates/server/src/proxy/compute/data_collection/mod.rs
crates/wasmtime/src/components/mod.rs
crates/wasmtime/src/payload.rs

Two changes:
- `from`, which is the provenance of the data collection call is now added to the event payload
- IP Anonymization  is now made by the component mod, to be prepared for the consent mapping
No issue

feat: add request infos

---

crates/server/src/proxy/compute/mod.rs

`enforce_no_store_policy` is used to enforce no-store cache-control header in the response for requests that can be computed. This policy now removes `expires`, `etag` and `last-modified` response headers to improve efficiency.

feat: improve enforce_no_store policy

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/commands/auth/login.rs
crates/cli/src/commands/auth/mod.rs
crates/cli/src/commands/auth/whoami.rs
crates/cli/src/commands/mod.rs
crates/cli/src/main.rs
crates/components/Cargo.toml
crates/components/src/auth/mod.rs
crates/components/src/auth/models.rs
crates/components/src/lib.rs

- Add a new crate `edgee-components` to house the code related to components authoring, building and publishing (and associated utilities)
- Add the new CLI command `auth` with two subcommands:
* `login`: Ask for an API token which can be created on the console and save it into a credentials file after validation
* `whoami`: Ask the API for who is the currently logged user, if any
```shell
$ edgee auth login
> Enter Edgee API token (you can create one at https://www.edgee.cloud/<username>/settings/tokens): ******
Logged as Julianne Hervier (julianne@edgee.cloud)
```
- EDGEE-230

cli: Add auth command

---

crates/server/src/proxy/context/proxy.rs
crates/server/src/tools/edgee_cookie.rs

When Edgee parses all the cookies, a cookie that contains an equal sign disappears from the cookies list

fix: cookie parsing is altered when a cookie contains an equal char

---

crates/server/src/proxy/controller.rs

The client-side events are collected on a dynamic URL, its path changing with each page change. 
We can see that these URLs show up in Google's search console. Even if they are not indexed, it would be better that bots ignore them. 
When a bot calls these URLs, we serve a 410 with a header `x-robots-tag: noindex, nofollow`. This doesn't seem to be enough, because it seems that the bot doesn't interpret the `x-robots-tag` header on a 410 error.
We now serve a 204
No issue

fix: event path 410 response becomes 204

---

crates/api-client/src/lib.rs

To test edgee with a local version of the api, two env vars can be used to change the API base url and the API token
No issue

feat: use env var to test api locally

---

crates/api-client/openapi.json
crates/components-runtime/src/data_collection/debug.rs
crates/components-runtime/src/data_collection/logger.rs

To reflect API changes: 
- data collection events endpoints now have a `/debug` prefix
- we now use an `Authorization` header instead of `x-api-secret` when debug info is sent to the API from data collection components

feat: data collection debug endpoints change

---

README.md
crates/api-client/openapi.json
crates/components-runtime/src/config.rs
crates/components-runtime/src/context.rs
crates/components-runtime/src/data_collection/debug.rs
crates/components-runtime/src/data_collection/mod.rs
crates/components-runtime/src/data_collection/payload.rs
crates/components-runtime/wit/deps.lock
crates/components-runtime/wit/deps.toml
crates/components-runtime/wit/deps/protocols/consent-mapping.wit
crates/components-runtime/wit/deps/protocols/data-collection.wit
crates/server/src/proxy/compute/data_collection/mod.rs
edgee.sample.toml

This pull request introduces changes to DataCollectionComponents configuration fields. 
- `name` becomes `id`
- `component` becomes `file`
- `credentials` and `config` are merged into `settings`
- `forward_client_headers` is removed (it is now a part of the `edgee_request` object return by components)
These changes affect edgee.toml components part:
```toml
[[components.data_collection]]
id = "amplitude" # could be a slug (edgee/amplitude) or an alias (amplitude)
file = "../components/amplitude-component/amplitude.wasm"
settings.amplitude_api_key = "xxxx"
settings.edgee_anonymization = true
settings.edgee_default_consent = "pending"
settings.edgee_track_event_enabled = false
settings.edgee_user_event_enabled = true
settings.edgee_page_event_enabled = true
```
- New wit protocol (with …

feat: new component configuration

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/components/mod.rs
crates/cli/src/commands/components/test.rs

First draft of `edgee components test`
TBD:

edgee components test cli

---

crates/cli/src/commands/auth/login.rs

This PR introduces an update of the Console links in order to add missing Tildes.

Update Link with Tidle Prefix

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/commands/components/init.rs
crates/cli/src/commands/components/new.rs
crates/cli/src/components/boilerplate.rs
crates/cli/src/components/boilerplates.rs
crates/cli/src/components/manifest.rs
crates/cli/src/components/mod.rs

feat: add new and init command

---

crates/api-client/openapi.json
crates/cli/src/commands/components/push.rs

push: prompt for public or private on creation

Prompt private or public on creation

---

crates/cli/src/commands/components/build.rs
crates/cli/src/commands/components/push.rs
crates/cli/src/logger.rs

- Build component on push when not built
- Update component metadata on push
- Print component URL on push
- Complete EDGEE-444, EDGEE-445 and EDGEE-455

feat(cli/components): improve push subcommand

---

crates/cli/src/commands/components/push.rs

- Update component metadata only when user confirmed the push
- Fix `public` field handling

refactor(cli/components): fix multiples reviews

---

crates/cli/src/commands/components/test.rs
crates/components-runtime/src/context.rs

When a component is ran through `edgee component test`, stdout of the component will be the one of the host
```
╰─$ ../../../edgee/target/release/edgee components test  --event-type page                                                                                                                                            
---------------------------------------------------
Calling page
hello from python wasm guest
```

component test: inherit stdout from host

---

Cargo.lock
Cargo.toml
crates/server/Cargo.toml
crates/server/src/proxy/compute/html.rs
crates/server/src/proxy/controller.rs
crates/server/src/proxy/mod.rs

Event paths rotated with each page view. The idea was interesting, but it added complexity to the SEO management of these URLs. 
In the end, we use the current url to collect an event, which makes data collection even more efficient.
For this, the sdk is bumped to version 5, and we no longer need the edge-path crate.
No issue related

feat: no more moving path

---

crates/api-client/openapi.json
crates/cli/src/commands/components/push.rs

This updates the component name via API on `edgee component push`.
We need to add the input parameter on the API side too.

Update component name on push (requires API release)

---

crates/cli/src/commands/components/test.rs

settings file format
```
[settings]
a="a"
b="sdsds"
```

components test: add settings-file

---

crates/cli/src/commands/components/check.rs
crates/cli/src/commands/components/init.rs
crates/cli/src/commands/components/new.rs
crates/cli/src/commands/components/push.rs
crates/cli/src/commands/components/test.rs
crates/cli/src/commands/update.rs

- CLI copyedit pass & shortering a few prompts
- add highlight/color to output where it makes sense
- standardize on tracing::info instead of println (unless it's a special case)
- add help for Editor use and customization (via env variable)

CLI UX improvements

---

crates/components-runtime/src/data_collection/context.rs
crates/components-runtime/src/data_collection/mod.rs

rework send event output data

---

crates/cli/src/commands/components/new.rs
crates/cli/src/commands/components/push.rs

Minor update to add some missing options descriptions.

Add missing command options descriptions

---

crates/api-client/openapi.json

/v1/users/me does not return a slug anymore

openapi.json: user slug is not provided anymore

---

Dockerfile
README-proxy.md

- update base rust image to stable (1.85.1)
- update entry point to use all CLI commands (not just serve)
- add note for macOS users (with arm chips)

Update Dockerfile and docs

---

crates/server/src/proxy/compute/mod.rs

When a page URL is unfortunately added in a <img> tag, Edgee processes it as a standard request that has to be computed. 
I added a new check in `do_process_payload` function, to look at the `sec-fetch-dest` request header. If this header tells the request has been made to get a specific kind of content (e.g an image), the computation is aborted.
No issue

fix: abort compute if sec-fetch-dest is for specific content

---

.github/workflows/release.yml

New GHA version for homebrew PR on release.

chore(ci): update GHA version to edgee-cloud/homebrew-edgee@v0.1.1

---

crates/server/src/proxy/compute/mod.rs

This PR adds 'empty' to the list of forbidden fetch destinations in the `do_process_payload` function. This change prevents the processing of requests that have an empty fetch destination, which could potentially be used for malicious purposes or cause unnecessary processing overhead.
- Added 'empty' to the list of forbidden fetch destinations in `fastly-edgee/src/proxy/compute/mod.rs`
This change improves security by preventing potential abuse through empty fetch destinations.

feat(security): add 'empty' to forbidden fetch destinations

---

.github/workflows/release.yml

Fix the release workflow to dispatch a PR workflow in the homebrew-edgee repo (instead of using a GH Action). This should fix the weird permission errors.

CI: convert homebrew-edgee GH Action to GH workflow dispatch

---

.github/workflows/release.yml

Context: you can't use the default GITHUB_TOKEN to trigger workflows (or anything else) in another repository. That requires using a personal access token with expanded scope. Imho, not worth messing with for now.
We can just trigger the homebrew workflow manually from here after each release: https://github.com/edgee-cloud/homebrew-edgee/actions/workflows/new-release-pr.yml

ci: remove homebrew workflow dispatch

---

.github/workflows/release.yml

Adds two new steps to the GitHub Actions workflow on release:
- Installs the Sentry CLI tool
- Uses Sentry CLI to upload debug information files to Sentry
The repo would need to have three new secrets and variables for the CI:
- `SENTRY_AUTH_TOKEN` secret
- `SENTRY_ORG` and `SENTRY_PROJECT` variables
- Closes EDGEE-632

ci(release): upload Debug Information Files to Sentry on release

---

.github/workflows/release.yml

Use the release build when sending the debug information files to Sentry

ci(release): use release build for Sentry Debug Information Files

---

crates/server/src/lib.rs

Propagate error on server start instead of dropping it, that should help not triggering some panic in the `tokio::select!` macro usage
in the `edgee serve` command.
- Fixes SENTRY-CLI-15

fix(server): don't drop error when starting the server

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/components/mod.rs
crates/cli/src/commands/components/serialize.rs
crates/components-runtime/src/config.rs
crates/components-runtime/src/data_collection/versions/v1_0_0/mod.rs
crates/components-runtime/src/data_collection/versions/v1_0_1/mod.rs
crates/components-runtime/src/edge_function/versions/v1_0_0/mod.rs

Add component serialization support for faster loading
Adds `edgee component serialize` command to pre-serialize WebAssembly components and unsafe deserialization support for improved startup performance.

Add component serialization support for faster loading
