- flake.nix
- src/main.rs
Basic architecture of HTTP proxy integrated with event processing queue.
@SachaMorard
> feat: http proxy

- src/main.rs
- src/providers.rs
Create basic endpoint configuration and integrate with proxy
FYI @SachaMorard
> feat: endpoint configuration

- src/main.rs
- src/providers.rs
forward http headers to upstream/target
FYI @SachaMorard
> feat: forward http headers

- src/config.rs
- src/main.rs
- src/providers.rs
- src/proxy.rs
extract proxy module from main.rs. in the future this module will expose a trait that can be implemented to support different proxy backends.
FYI @SachaMorard
> refactor: extract proxy module

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/entrypoint.rs
configuration supports advanced routing rules
> feat: advanced routing rules

- src/entrypoint.rs
- src/monitor.rs
Replace DEBUG logs that should be INFO
> feat: add info logs

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/entrypoint.rs
- src/entrypoint/web.rs
- src/entrypoint/websecure.rs
Accept a debug header and expose proxy info in response when toggled
> feat: add debug header

- README.md
A few messaging improvements and fixed a couple of typos.
N/A
> docs: update README - copyediting & typos

- Cargo.lock
- Cargo.toml
Removes two unused dependencies (`clap` and `simple_logger`) left from commit 5decc7d28f7321b247c182159e5d8f3d87ce920e.
N/A.
> chore(deps): remove unused deps

- src/config.rs
Adds one configuration validator for checking that no two routers point to the same domain.
When running with the following config:
```toml
[log]
level = "info"
[http]
address = "0.0.0.0:8080"
force_https = true
[https]
address = "0.0.0.0:8443"
cert = "local/cert/edgee.pem"
key = "local/cert/edgee.key"
[monitor]
address = "0.0.0.0:8222"
[[destinations.data_collection]]
name = "amplitude"
component = "local/wasm/amplitude.wasm"
credentials.amplitude_api_key = "..."
[[destinations.data_collection]]
name = "google analytics"
component = "local/wasm/ga.wasm"
credentials.ga_measurement_id = "..."
[[destinations.data_collection]]
name = "segment"
component = "local/wasm/segment.wasm"
credentials.segment_project_id = "..."
credentials.segment_write_key = "..."
[[routing]]
domain = …
```
> feat: add config validations

- src/entrypoint.rs
- src/html.rs
Better way to get the sdk file and render it
https://github.com/edgee-cloud/edgee/issues/29
> fix: #29, sdk path does not render the good file

- Makefile
- src/config.rs
- src/tools/crypto.rs
- src/tools/path.rs
- src/tools/real_ip.rs
> test: add first unit tests

- Cargo.lock
- Cargo.toml
- src/entrypoint.rs
handle brotli ("br") encoding.
Takes around 120ms on analytics-with-edgee.html page (including network time), but only 16ms if proxy is built in release.
Fixes issue #34
> Brotli encoding

- src/entrypoint.rs
Replace `x-edgee-process` header by `x-edgee`
> chore: replace x-edgee-process header by x-edgee

- src/config.rs
- src/entrypoint.rs
- src/entrypoint/routing_context.rs
- src/logger.rs
- src/tools/crypto.rs
- src/tools/edgee_cookie.rs
Add `do_only_proxy` method to better organize the logic 
#48
> chore: add do_only_proxy method

- src/entrypoint.rs
There were specific things regarding the way edgee handles path and URL queries. We had to fix it.
#51
> chore: better handle path and query

- Cargo.lock
- Cargo.toml
- README.md
- edgee.sample.toml
- src/config/config.rs
- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/components.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/compute/data_collection/mod.rs
- src/proxy/compute/data_collection/payload.rs
- src/proxy/context/incoming.rs
- src/proxy/context/proxy.rs
- src/proxy/controller/controller.rs
- src/proxy/proxy.rs
- src/tools/real_ip.rs
- wit/protocols.wit
Connect all event types, and ensure that the proxy can also use the data-collection enterprise api.
#57
> feat: add all edgee event, and plug enterprise data-collection-api

- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/proxy.rs
- Add info logs on each requests to better see whats happen
- Remove useless debug log
- use tracing:: instead of log::
No issue
> feat: improve info logs

- src/proxy/context/proxy.rs
- src/tools/edgee_cookie.rs
When a request is received by edgee, then transmitted to a backend server, some cookies may disappear en route. This means that the backend doesn't receive all the cookies it was expecting. 
In the proxy context, we rebuild the full cookie header.
#62
> fix: Cookies disappear from requests sent to upstream

- src/proxy/compute/html.rs
html parser doesn't exclude comments. 
> fix: html parser comment

- src/tools/real_ip.rs
> fix: real_ip unit test

- src/proxy/compute/compute.rs
- src/tools/cacheable.rs
- src/tools/mod.rs
Improve cacheability detection logic
#70
> feat: improve cacheability detection logic

- src/config/config.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/compute/data_collection/payload.rs
- src/proxy/context/incoming.rs
- src/proxy/controller/controller.rs
- src/server.rs
Optimize imports, just to be clean ;)
> chore: optimize imports

- Cargo.lock
- src/proxy/context/incoming.rs
Fix: warning about url() method not used
no issue
> fix: warning, url method not used

- src/config/config.rs
- src/main.rs
- src/monitor.rs
- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/components.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/compute/data_collection/mod.rs
- src/proxy/compute/data_collection/payload.rs
- src/proxy/compute/html.rs
- src/proxy/context/proxy.rs
- src/proxy/context/routing.rs
- src/proxy/controller/controller.rs
- src/proxy/mod.rs
- src/proxy/proxy.rs
- src/server.rs
- src/tools/cacheable.rs
- src/tools/crypto.rs
- src/tools/edgee_cookie.rs
- src/tools/mod.rs
- src/tools/path.rs
- src/tools/real_ip.rs
Using the [Rust Code Style](https://doc.rust-lang.org/stable/style-guide/) as standard code formatting for Rust projects is a good convention and also allows contributors to be on a uniform basis for contributing
It also helps preventing "accidental typo commits" from occurring when one has an editor with "auto-format" enabled (I do :smile:)
Which is also why the new CI workflows now checks for code formatting using `cargo fmt --check` so the code formatting is "softly" enforced (as opposed to a pre-commit style of checks enforcing)
None
> chore: Format source code with cargo-fmt

- src/proxy/compute/data_collection/components.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/tools/edgee_cookie.rs
- wit/protocols.wit
- Improve logs coming from data-collection
- update wit
No issue
> feat: improve data-collection logs and update wit

- README.md
- install.sh
- Add install script usage in `README.md`
- Improve install script
* Add shiny colors
* Print usage help text when successful
- #86
> chore: Improve install script and document it

- src/proxy/compute/data_collection/components.rs
- wit/protocols.wit
Little changes on WIT protocol
- remove `destinations` field, because it is not used by data collection components
- `session.first_seen`  and `session.last_seen` type change
No issue
> feat: changes on wit protocol

- Cargo.lock
- Cargo.toml
- src/proxy/compute/data_collection/components/context.rs
Update the `wasmtime` dependency:
- Bring fix for the CVE-2024-47763 vulnerability
- Get a more up-to-date version of wasmtime
> chore(deps): Update wasmtime to 25.0.2

- src/config/config.rs
- src/proxy/compute/data_collection/components/context.rs
Adapt wasmtime engine and configuration to handle more WASM components using other languages (for instance: Javascript with ComponentizeJS)
Also add a config entry for caching pre-instantiated modules since it takes some compute time (and JavaScript WASM components are **heavy**)
> Adapt WASM Components engine for more languages

- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/controller/controller.rs
- src/proxy/proxy.rs
Simple naming and type alignment 
no issue
> chore: naming alignemnt

- src/tools/edgee_cookie.rs
The `get` function of the edgee_cookie script didn't work correctly. In case of multiple cookies in the request, the function couldn't detect `edgee` cookie.
No issue
> fix: edgee cookie detection

- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/context/incoming.rs
- src/proxy/context/proxy.rs
- src/proxy/context/routing.rs
- src/proxy/controller/controller.rs
- src/proxy/mod.rs
- src/proxy/proxy.rs
- src/tools/edgee_cookie.rs
I changed the incoming context to use the request information better everywhere in the code. 
#110
> Eoss 36 improve request arguments

- src/proxy/compute/data_collection/data_collection.rs
Little bug in Path definition for data-collection
No issue
> fix: little bug with path

- src/proxy/compute/compute.rs
- src/proxy/compute/data_collection/data_collection.rs
- src/proxy/controller/controller.rs
Add provenance info of the event (edge, client or third) and put it in a data collection API header 
no issue
> feat: add provenance info of the event (edge, client, third)

- src/proxy/compute/data_collection/data_collection.rs
Add `X-Edgee-Host` header (host of the previous request) to the data-collection API call.
No issue
> feat: add host in the data-collection api call

- Cargo.lock
- Cargo.toml
- README.md
- src/proxy/compute/html.rs
Title tag extraction didn't work properly with one or more character(s) with accent
No issue
> fix: title tag

- README.md
A few changes to clarify the main doc:
- update 0.4.X version
- new LinkedIn contact
- mention `local/cert` and `local/wasm` folder for local development
- fixed port 443 for HTTPS (can't be the same as HTTP)
- a bit of explanation for routing logic and path rewrite
> Improve main doc 

- Cargo.lock
- Cargo.toml
Fix dependabot alert
Wasmtime doesn't fully sandbox all the Windows device filenames
https://github.com/edgee-cloud/edgee/security/dependabot/4
> deps: bump wasmtime

- src/proxy/compute/html.rs
This PR improves the HTML Document parsing by doing the following:
- Stop parsing the document when we have extracted all the data we need (mainly: SDK tag, data layer tag if exists, `<title>`, canonical and keywords meta tags)
- Considers the `<head>`-only tags as non-defined/empty when they're not present
The "trade-off" for this improved parsing function is that the Edgee SDK tag *must* be present early in the document, since that's the main "exit point" of the function.
Benchmark results using https://github.com/edgee-cloud/edgee-benches repository:
```shell
$ cargo criterion base.*/printemps
Finished `bench` profile [optimized + debuginfo] target(s) in 0.08s
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s …
```
> perf(proxy/compute): Improve HTML Document parsing

- Dockerfile
Docker build needs rust > 1.80 
No issue
> fix: rust version in Dockerfile

- .github/workflows/release.yml
The `command` input was set to a wrong value
Also fix the `houseabsolute/actions-rust-cross` action version to avoid further surprises
> ci: Fix binary release workflow

- crates/wasmtime/src/components/mod.rs
The referer header was wrongly defined on the data collection calls. 
It has to be inserted like an analytics client-side SDK could do
> fix: referer for data collection call

- crates/server/src/proxy/context/proxy.rs
To avoid overloading the cookie headers sent to the backend, we delete the `edgee` and `edgee_u` cookies from the request originally sent.
No issue
> chore: cleanup cookies

- Cargo.lock
- Cargo.toml
- Makefile
- crates/server/src/config.rs
- crates/server/src/proxy/compute/data_collection/mod.rs
- crates/server/src/tools/edgee_cookie.rs
- crates/wasmtime/src/components/config.rs
- crates/wasmtime/src/components/convert.rs
- crates/wasmtime/src/components/mod.rs
- crates/wasmtime/src/payload.rs
- crates/wasmtime/wit/deps.lock
- crates/wasmtime/wit/deps.toml
- crates/wasmtime/wit/deps/protocols/protocols.wit
Added consent management functionality to handle user privacy preferences across the data collection pipeline. This implementation ensures proper handling of user consent states and applies appropriate data anonymization based on consent status.
- Added a Consent enum in payload.rs with three states:
- Pending
- Granted
- Denied
- Updated EdgeeCookie struct to store consent state
- Added consent handling in cookie management functions
- Implemented consent state persistence across sessions
- Modified data collection process to respect consent settings:
- Added consent checks before processing user data
- Implemented anonymization for users who haven't granted consent
- Added consent state to event context
- Added consent-related configuration options:
- default_consent setting to specify …
> feat: consent mapping

- crates/wasmtime/src/components/mod.rs
Fix anonymization.
Sometimes, the anonymization wasn't working correctly because of variable reasignation in a loop.
No issue
> fix: anonymization

- crates/server/src/proxy/compute/data_collection/mod.rs
- crates/wasmtime/src/components/mod.rs
- crates/wasmtime/src/payload.rs
Fix borrowing and mutable event object bugs
No issue
> fix: anonymization and consent

- README.md
- install.sh
> chore: change docs url

- crates/wasmtime/src/components/convert.rs
- crates/wasmtime/src/components/mod.rs
- crates/wasmtime/wit/deps.lock
- crates/wasmtime/wit/deps.toml
- crates/wasmtime/wit/deps/protocols/protocols.wit
> Revert "feat: id continuity wit compatibility"

- Makefile
- package-lock.json
This PR introduces a fix for the `Make dev.up` command, so it runs correctly on linux adding the `serve` command.
https://linear.app/edgee/issue/EDGEE-302/[edgee]-make-devup-command-should-work-on-linux
> Update dev.up Make Command

- crates/wasmtime/src/components/mod.rs
Session could be doubled in case of multiple events in one payload. To prevent it, we add 1 second to the event timestamp from the second event of an event loop
No issue
> fix: session could be doubled in case of multiple event in one payload

- Cargo.lock
- Cargo.toml
- Makefile
- crates/server/Cargo.toml
- crates/server/src/proxy/compute/html.rs
- crates/server/src/tools/cacheable.rs
- crates/server/src/tools/crypto.rs
- crates/server/src/tools/edgee_cookie.rs
- crates/server/src/tools/real_ip.rs
Add new tests to increase coverage (from 13% to 21%).
Before:
```bash
Filename                                            Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api-client/src/lib.rs                                     7                 7     0.00%           4                 4     0.00%          24                24     0.00%           0                 0         -
cli/src/commands/auth/login.rs                           14                14     0.00%           2 …
```
> Add new unit tests for server crate

- Cargo.lock
- Cargo.toml
> chore: Bump version (0.7.0)

- .github/CODEOWNERS
- crates/server/src/proxy/compute/html.rs
- crates/server/src/tools/edgee_cookie.rs
Fix little clippy issues, but nothing really important
Change codeowner
> fix: clippy little alerts

- crates/server/src/proxy/compute/data_collection/payload.rs
- crates/server/src/proxy/compute/mod.rs
- crates/server/src/proxy/context/incoming.rs
Little improvements suggested by clippy
No issue
> chore: clippy little fixes

- crates/components-runtime/src/config.rs
- crates/components-runtime/src/data_collection/context.rs
- crates/components-runtime/src/data_collection/debug.rs
- crates/components-runtime/src/data_collection/logger.rs
- crates/components-runtime/src/data_collection/mod.rs
Components-runtime improvements:
- Fix a component configuration default value problem
- Replace RequestInfo with EventContext
- Better way of handling EventContext value borrowing
- Add a log to log_outgoing_event
No issue
> chore: components-runtime improvements

- crates/components-runtime/src/config.rs
- crates/components-runtime/src/data_collection/mod.rs
add an option for data collection component to skip forwarding headers from the client to the data collection endpoint
> add forward_header option to data collection component

- README.md
- crates/server/src/config.rs
- crates/server/src/proxy/context/mod.rs
- crates/server/src/proxy/context/redirection.rs
- crates/server/src/proxy/controller.rs
- crates/server/src/proxy/mod.rs
In this Pull Request, we add the capacity for redirections. For now they are quite basic but can be configured through the TOML file 
```toml
[[redirections]]
origin = "http://example.com/old-path"
destination = "http://example.com/new-path"
```
> feat: add redirection basic logic

- crates/api-client/openapi.json
- crates/cli/src/commands/components/init.rs
- crates/cli/src/commands/components/push.rs
- crates/cli/src/components/manifest.rs
- Rename setting field type `boolean` to `bool`
- Use kebab-style names everywhere in the manifest
- Rename `config-fields` to `settings` in manifest
- EDGEE-450
> fix(components): multiples fixes for components CLI

- crates/components-runtime/src/data_collection/mod.rs
native_cookie_ids is now based on components slugs
> chore: new native cookies

- crates/cli/src/commands/components/push.rs
> refactor(cli/components): update component registry URL

- Cargo.lock
- Cargo.toml
> chore: Release 0.8.1

- crates/cli/src/commands/components/push.rs
> feat(cli/components): check version asap on push

- Cargo.lock
- Cargo.toml
> release: 0.8.2

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/commands/components/test.rs
component test: add a --curl switch to get a curl command to test the output
> component test: add a --curl switch to get a curl command to test the output

- crates/cli/src/commands/components/check.rs
- crates/cli/src/commands/components/push.rs
components: run check before push
> components: run check before push

- crates/cli/src/commands/components/check.rs
> check: allow --filename

- README.md
- crates/cli/src/commands/components/new.rs
- crates/cli/src/components/boilerplate.rs
https://github.com/user-attachments/assets/4b4baf07-7891-4f48-ab38-28d0425a8ae7
> feat(cli-components-new): add possibility to use argument to shortcut command

- crates/cli/src/commands/components/test.rs
- crates/components-runtime/src/data_collection/mod.rs
component test: forward client headers
> Component test forward headers

- Cargo.lock
- Cargo.toml
> 0.8.3: release

- README.md
Update README to document latest features.
> Add new CLI features

- .github/workflows/release.yml
- Add builds for Linux (static) and Windows
- Resolves EDGEE-485 and EDGEE-471
> ci: Add static build for Linux and Windows

- Cargo.toml
- crates/api-client/Cargo.toml
- crates/cli/Cargo.toml
- crates/components-runtime/Cargo.toml
- crates/server/Cargo.toml
- install.sh
- Use musl build for the install script
- Add README into packages metadata (so that crates.io displays it)
- Add [cargo-binstall](https://github.com/cargo-bins/cargo-binstall/tree/main) metadata (so `cargo binstall edgee` would work)
> chore: Improve packaging and distribution

- Cargo.lock
- Cargo.toml
> release: 0.8.4

- Cargo.lock
- crates/components-runtime/Cargo.toml
- crates/components-runtime/src/context.rs
- crates/components-runtime/src/data_collection/mod.rs
add a option for the component runtime to await all components requests
> Component runtime blocking

- Cargo.lock
- Cargo.toml
> release: 0.8.5

- crates/components-runtime/src/data_collection/debug.rs
- crates/components-runtime/src/data_collection/mod.rs
return status of the provider calls
> components-runtime: return send events status in future

- Cargo.lock
- Cargo.toml
> edgee: update to 0.8.6

- crates/api-client/openapi.json
- crates/cli/src/components/boilerplate.rs
- crates/cli/src/components/manifest.rs
Add `conversion-api` component subcategory
> feat: add conversion-api component subcategory

- README.md
Add ad-hoc documentation for all shell types (each one is different lol).
> docs: update generate-shell-completion for all supported shells

- Cargo.lock
- Cargo.toml
> chore: release 0.8.7

- Cargo.lock
- Cargo.toml
> edgee: update to 0.8.8

- Cargo.lock
- Cargo.toml
- crates/server/src/config.rs
- crates/server/src/proxy/compute/html.rs
- crates/server/src/proxy/controller.rs
> feat: sdk autocapture

- Cargo.lock
- Cargo.toml
Bump Edgee SDK to version v1.6.1
> chore: bump sdk to v1.6.1

- crates/api-client/src/auth.rs
- crates/api-client/src/lib.rs
- crates/cli/src/commands/auth/login.rs
- crates/cli/src/commands/auth/whoami.rs
- crates/cli/src/commands/components/push.rs
edgee: credentials: handle profiles
login: can save credentials to profiles
push: can push to a given profile
> edgee: credentials: handle profiles

- Cargo.lock
- Cargo.toml
> edgee: release 0.9.0

- crates/components-runtime/src/data_collection/mod.rs
> fix: native cookies

- crates/api-client/src/auth.rs
- crates/api-client/src/lib.rs
auth: bypass credentials.toml if login env vars are provided
> auth: bypass credentials.toml if login env vars are provided

- README.md
- add new install methods
- update command outputs
- add link to manifest file docs
> Update README with latest features and outputs

- .editorconfig
I pushed my local EditorConfig file by error...
> chore: remove broken file added by error

- crates/components-runtime/src/data_collection/context.rs
- crates/components-runtime/src/data_collection/debug.rs
- crates/components-runtime/src/data_collection/logger.rs
- crates/components-runtime/src/data_collection/payload.rs
Add as_number to the data collection payload and the logs
> feat: add as_number

- Cargo.lock
- Cargo.toml
> bump workspace and crates to 1.1.0

- crates/cli/src/components/manifest.rs
- crates/cli/src/config.rs
- crates/components-runtime/src/data_collection/mod.rs
> chore: fix lint and clippy issues

- crates/cli/src/commands/components/fetch_wit.rs
- crates/cli/src/commands/components/mod.rs
- crates/cli/src/components/wit.rs
- Add `components fetch-wit` command to pull WIT files if needed
Resolves EDGEE-538
> feat(cli/components): add fetch-wit command

- crates/api-client/openapi.json
Update openapi.json to reflect API changes (override cache)
> feat: override-cache

- crates/components-runtime/src/context.rs
use wasmtime local caching to speedup reuse of already built components
> components: use wasmtime cache

- Cargo.lock
- Cargo.toml
- crates/components-runtime/src/context.rs
fix crash if defualt wasmtime cache is not available
edgee: update to v1.1.2
> edgee: update to v1.1.2

- crates/components-runtime/src/consent_management/versions/mod.rs
- crates/components-runtime/src/data_collection/versions/mod.rs
edgee.toml: correctly deserialize wit version
> edgee.toml: correctly deserialize wit version

- crates/cli/src/commands/components/build.rs
- crates/cli/src/commands/components/check.rs
- crates/cli/src/commands/components/new.rs
- crates/cli/src/commands/components/test.rs
- crates/components-runtime/src/config.rs
- crates/components-runtime/src/consent_management/versions/mod.rs
- crates/components-runtime/src/consent_management/versions/v1_0_0/mod.rs
- crates/components-runtime/src/context.rs
consent management: cleanup cmp components
> consent management: cleanup cmp components

- Cargo.lock
- Cargo.toml
> update to 1.2.1

- crates/cli/src/commands/components/check.rs
- crates/cli/src/components/boilerplate.rs
> Fix consent management typos

- crates/api-client/openapi.json
- crates/cli/src/commands/components/init.rs
- crates/cli/src/commands/components/push.rs
- crates/cli/src/components/manifest.rs
Add options field to settings fields
> feat: add settings options field

- crates/api-client/openapi.json
remove old unused api variable
> remove old unused api variable

- Cargo.lock
- Cargo.toml
- crates/server/src/proxy/compute/html.rs
- crates/server/src/proxy/controller.rs
> chore: bump edgee sdk v1.7.0

- crates/cli/src/commands/components/check.rs
- Fix `check` subcommand for Consent Mapping components
> fix(cli/check): fix check command

- crates/cli/src/commands/auth/whoami.rs
- crates/cli/src/commands/components/test.rs
- crates/cli/src/config.rs
- crates/components-runtime/src/data_collection/debug.rs
- crates/components-runtime/src/data_collection/mod.rs
- crates/server/src/config.rs
- crates/server/src/proxy/compute/data_collection/mod.rs
- crates/server/src/proxy/compute/mod.rs
- crates/server/src/proxy/context/body.rs
- crates/server/src/proxy/context/proxy.rs
- crates/server/src/proxy/controller.rs
- crates/server/src/proxy/mod.rs
- crates/server/src/tools/cacheable.rs
- Fix many nightly clippy warnings
- Using nightly allows getting ahead for future new lints before they land
> chore: fix many nightly clippy warning

- Cargo.lock
- Cargo.toml
> chore: release 1.2.5

- Cargo.toml
> chore: bump edgee-sdk version

- Cargo.lock
- crates/components-runtime/Cargo.toml
- crates/components-runtime/src/config.rs
- crates/components-runtime/src/data_collection/mod.rs
- crates/components-runtime/src/data_collection/payload.rs
In this PR we have added a logic to be able to add conditional data manipulation and event filtering 
> feat: add event filtering and data manipulation

- Cargo.lock
- Cargo.toml
> feat: update crates version

- Cargo.lock
- Cargo.toml
> chore: bump edgee-sdk to v1.7.3

- Cargo.lock
- crates/cli/src/commands/components/test.rs
- crates/components-runtime/Cargo.toml
- crates/components-runtime/src/data_collection/mod.rs
- crates/components-runtime/src/data_collection/versions/v1_0_0/execute.rs
> feat: add real client headers

- crates/cli/src/main.rs
> cli: main.rs: return error code to shell

- Cargo.lock
- Cargo.toml
> update to 1.2.10

- crates/cli/src/commands/components/push.rs
component push: display latest available version on the registry
> component push: display latest available version on the registry

- crates/cli/src/commands/components/test.rs
> component test: remove unreachable case

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/commands/components/test.rs
Component test: patch events with current timestamp
> Component test: patch events with current timestamp

- Cargo.lock
- Cargo.toml
> update to 1.2.12

- Cargo.lock
- crates/cli/src/commands/components/test/test_data_collection_v1_0_1.rs
- crates/cli/src/commands/components/test/test_edge_function_v1_0_0.rs
- crates/components-runtime/Cargo.toml
- crates/components-runtime/src/data_collection/mod.rs
- crates/components-runtime/src/edge_function/mod.rs
- crates/server/src/proxy/context/incoming.rs
- crates/server/src/proxy/mod.rs
- edgee.sample.toml
> edge-function: oss edition

- Cargo.lock
- Cargo.toml
> feat: bump version

- crates/cli/src/commands/components/test/test_edge_function_v1_0_0.rs
> test: edge-function: fix missing settings

- crates/server/src/proxy/mod.rs
> feat: add method activation on fn components

- crates/server/src/proxy/mod.rs
Do only proxy when response is a client error but 404
> feat: client error proxy

- crates/cli/src/commands/components/check.rs
- crates/cli/src/commands/components/serialize.rs
- crates/cli/src/commands/components/test/test_edge_function_v1_0_0.rs
- crates/components-runtime/src/config.rs
- crates/components-runtime/src/context.rs
- crates/components-runtime/src/data_collection/versions/v1_0_0/mod.rs
- crates/components-runtime/src/data_collection/versions/v1_0_1/mod.rs
- crates/components-runtime/src/edge_function/versions/v1_0_0/mod.rs
- crates/components-runtime/src/helpers.rs
- crates/components-runtime/src/lib.rs
• Refactored component loading to support multiple source types (file, binary, serialized)
• Added `ComponentSource` struct to handle different component loading methods
• Unified component serialization logic with generic `serialize_component` method
• Improved component loading performance with optimized instantiation paths
> Refactor component loading with flexible source handling

- Cargo.lock
- Cargo.toml
> release version 1.2.20

- crates/api-client/openapi.json
- crates/cli/src/components/manifest.rs
Replace SDK Gateway reference by JS Gateway
> chore: replace sdk gateway by js gateway

- crates/components-runtime/src/data_collection/payload.rs
> feat: add doesnt start with

- crates/api-client/openapi.json
update openapi because of a bug with editor users
Editor role is missing in some enums
> fix: update openapi because of a bug with editor users

- crates/api-client/openapi.json
Add project `type` field in OpenAPI specs
> feat: projet types

- Cargo.lock
- Dockerfile
- Update Rust version in the `Dockerfile` (some dependencies requires a recent version)
- Update `aws-lc-rs` dependency (include fix for https://github.com/aws/aws-lc-rs/issues/889 )
> Fix release CI

- crates/components-runtime/src/data_collection/mod.rs
> feat: add fbp and fbc injection when meta-capi
